In [1]:
import numpy as np

# Разминка

## Задача №1

Создать массив размера n x m, в котором граница толщиной 1 будет заполнена числами 1, а всё остальное - 0

In [2]:
def task1(n: int, m: int) -> np.array:
    pass

In [3]:
print(task1(4, 4))
print(task1(4, 7))

None
None


## Задача №2

Заменить элементы двумерной матрицы лежащие в диапазоне [a, b] на нули.

In [4]:
def task2(arr: np.array, a: int, b: int) -> np.array:
    pass

In [5]:
print(task2(np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]), 
                      4, 7))

None


# Axis

![numpyaxis1.jpg](sources/numpyaxis1.jpg)

In [12]:
a = np.arange(0, 24).reshape((3, -1))
print(f'Исходный массив размер {a.shape}:\n', a)

Исходный массив размер (3, 8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [13]:
print('Сложение с парметром axis = 0:\n', np.sum(a, axis=0))

Сложение с парметром axis = 0:
 [24 27 30 33 36 39 42 45]


In [14]:
print('Сложение с парметром axis = 1:\n', np.sum(a, axis=1))

Сложение с парметром axis = 1:
 [ 28  92 156]


In [15]:
print('Сложение с парметром axis = 2:\n', np.sum(a, axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [16]:
print('Сложение с парметром axis = None:\n', np.sum(a, axis=None))

Сложение с парметром axis = None:
 276


In [19]:
print('Сложение с парметром axis = -1:\n', np.sum(a, axis=-1))

Сложение с парметром axis = -1:
 [ 28  92 156]


In [20]:
print('Сложение с парметром axis = -2:\n', np.sum(a, axis=-2))

Сложение с парметром axis = -1:
 [24 27 30 33 36 39 42 45]


![cube.png](sources/cube.png)

In [24]:
a = np.arange(0, 24).reshape(2, 3, -1)
print(f'Исходный массив размер {a.shape}:\n', a)

Исходный массив размер (2, 3, 4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
print('Сложение с парметром axis = 0:\n', np.sum(a, axis=0))

Сложение с парметром axis = 0:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [26]:
print('Сложение с парметром axis = 1:\n', np.sum(a, axis=1))

Сложение с парметром axis = 1:
 [[12 15 18 21]
 [48 51 54 57]]


In [27]:
print('Сложение с парметром axis = 2:\n', np.sum(a, axis=2))

Сложение с парметром axis = 2:
 [[ 6 22 38]
 [54 70 86]]


In [28]:
print('Сложение с парметром axis = None:\n', np.sum(a, axis=None))

Сложение с парметром axis = None:
 276


In [29]:
print('Сложение с парметром axis = 3:\n', np.sum(a, axis=3))

AxisError: axis 3 is out of bounds for array of dimension 3

## Задача 3

Магическим квадратом порядка n называется квадратная матрица размером n x n, состоящая из n^2 различных чисел так, что суммы по каждому столбцу, каждой строке и каждой из двух диагоналей равны между собой. Проверить, является ли заданная квадратная матрица магическим квадратом.

In [30]:
def task3(square: np.array) -> bool:
    pass

In [31]:
print(task3(np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
            )
    )

None


In [32]:
print(task3(np.array([[2, 7, 6],
                      [9, 5, 1],
                      [4, 3, 8,]])
            )
        )

None


In [33]:
print(task3(np.full((3, 3), 3)))

None


## Нетривиальное добавление элементов массива

In [36]:
a = np.array([])
b = np.arange(24).reshape(3, -1)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [35]:
np.append(a, b)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [39]:
np.append(a, b, axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [52]:
a = np.empty((0, 3))
b = np.arange(3)
c = np.arange(3, 6)

In [53]:
a = np.append(a, b, axis=0)
a = np.append(a, c, axis=0)
a

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [54]:
a = np.append(a, np.array([b]), axis = 0)
a = np.append(a, np.array([c]), axis = 0)
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [55]:
a = np.empty((0, 3))
a = np.append(a, b[np.newaxis, ...], axis = 0)
a = np.append(a, c[np.newaxis, ...], axis = 0)
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [56]:
a = np.empty((0, 3))
b = np.arange(4)
np.append(a, b[np.newaxis, ...], axis = 0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [63]:
a = np.array([])
b = np.arange(3)
c = np.arange(3, 6)

In [64]:
a = np.hstack((a, b))
print(a)
a = np.vstack((a, c))
print(a)

[0. 1. 2.]
[[0. 1. 2.]
 [3. 4. 5.]]


In [67]:
import numpy as np
 

arr = np.arange(12).reshape(3, 4)
print("arr : \n", arr)
print("Shape : ", arr.shape)
 

a = np.delete(arr, 1, axis=0)
print("\ndeleteing arr 2 times : \n", a)
print("Shape : ", a.shape)
 

a = np.delete(arr, 1, axis=1)
print("\ndeleteing arr 2 times : \n", a)
print("Shape : ", a.shape)

arr : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4)

deleteing arr 2 times : 
 [[ 0  1  2  3]
 [ 8  9 10 11]]
Shape :  (2, 4)

deleteing arr 2 times : 
 [[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
Shape :  (3, 3)


AxisError: axis 2 is out of bounds for array of dimension 2